---
- name: play to set message of the day
  hosts: all
  become: yes
  tasks:
    - name: set motd file
      template:
        src: mm.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: 0644
...
